package com.plexon.gpflags;

import com.plexon.gpflags.config.SchemaVersion;
import org.junit.jupiter.api.Test;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class Phase2ContractTest {
    @Test void schemaVersionAcceptsLegacyAndCurrentButRejectsFuture() { assertEquals(1, SchemaVersion.requireSupported(null, 1, 2, "test")); assertEquals(2, SchemaVersion.requireSupported(2, 1, 2, "test")); assertThrows(IllegalStateException.class, () -> SchemaVersion.requireSupported(3, 1, 2, "test")); assertThrows(IllegalArgumentException.class, () -> SchemaVersion.requireSupported("2", 1, 2, "test")); }
    @Test void candidateVersionAndJava25AreExact() throws Exception { String build = text("build.gradle.kts"); assertTrue(build.contains("version = \"1.1.0-rc.1\"")); assertTrue(build.contains("JavaLanguageVersion.of(25)")); assertTrue(build.contains("major == 69")); }
    @Test void stableFlagIdsRemainCompatible() throws Exception { String flags = text("src/main/java/com/plexon/gpflags/flag/ClaimFlag.java"); for (String id : List.of("natural-mobs", "spawner-mobs", "pvp", "building", "interactions", "containers", "explosions", "fire", "crop-trampling", "mob-griefing")) assertTrue(flags.contains("\"" + id + "\""), id); assertTrue(flags.contains("Duplicate claim flag id")); }
    @Test void strictConfigValidationRejectsUnknownAndUnsafeInputs() throws Exception { String validator = text("src/main/java/com/plexon/gpflags/config/ConfigValidator.java"); assertTrue(validator.contains("Unknown flag id in")); assertTrue(validator.contains("must be boolean")); assertTrue(validator.contains("must be a string list")); assertTrue(validator.contains("world-defaults key must be a world UUID")); assertTrue(validator.contains("safe single folder name")); }
    @Test void persistenceIsSchemaGuardedAndUnknownFlagsAreQuarantined() throws Exception { String store = text("src/main/java/com/plexon/gpflags/flag/FlagStore.java"); assertTrue(store.contains("SchemaVersion.requireSupported")); assertTrue(store.contains("quarantine.claims.")); assertTrue(store.contains("CURRENT_SCHEMA = 2")); assertTrue(store.contains("prepareCandidate()")); assertTrue(store.contains("applyCandidate(Candidate candidate)")); }
    @Test void legacyMigrationIsBackedUpAndDoesNotRequireLegacyPlugin() throws Exception { String store = text("src/main/java/com/plexon/gpflags/flag/FlagStore.java"); assertTrue(store.contains("migration-backups")); assertTrue(store.contains("legacy-import.complete")); assertTrue(store.contains("file.exists()) return")); assertTrue(store.contains("Files.copy(legacy, backup")); }
    @Test void authoritativeMutationStillRechecksOwnerAdminAuthorization() throws Exception { String service = text("src/main/java/com/plexon/gpflags/flag/FlagService.java"); assertTrue(service.contains("claims.canManage(actor, claim)")); assertTrue(service.contains("NOT_AUTHORIZED")); assertTrue(service.contains("Bukkit.isPrimaryThread()")); }
    @Test void reloadPreparesCandidatesBeforePublishingAndInvalidatesMenus() throws Exception { String main = text("src/main/java/com/plexon/gpflags/PlexonGPFlags.java"); int configCandidate = main.indexOf("RuntimeSettings nextSettings"); int storeCandidate = main.indexOf("FlagStore.Candidate nextStore", configCandidate); int closeMenus = main.indexOf("menus.closeAll()", storeCandidate); int assignSettings = main.indexOf("settings = nextSettings", closeMenus); assertTrue(configCandidate >= 0 && storeCandidate > configCandidate); assertTrue(closeMenus > storeCandidate && assignSettings > closeMenus); assertTrue(main.contains("store.applyCandidate(previousStore)")); assertTrue(main.contains("configurationGeneration++")); }
    @Test void guiIsActorGenerationBoundAndMutationRevalidatesClaim() throws Exception { String guard = text("src/main/java/com/plexon/gpflags/gui/MenuSessionGuard.java"); String menu = text("src/main/java/com/plexon/gpflags/gui/MenuService.java"); assertTrue(guard.contains("UUID actor, long generation")); assertTrue(guard.contains("plugin.configurationGeneration()")); assertTrue(menu.contains("event.setCancelled(true)")); assertTrue(menu.contains("claims.byId(holder.claimId)")); assertTrue(menu.contains("claims.canManage(player, claim)")); }
    @Test void protectionNeverUncancelsAndPlayerCropBypassIsConsistent() throws Exception { String protection = text("src/main/java/com/plexon/gpflags/protection/ProtectionListener.java"); assertTrue(protection.contains("ignoreCancelled = true")); assertTrue(protection.contains("boolean bypass = claims.bypassesPlayerRestriction")); assertTrue(protection.contains("farmland && !bypass")); assertTrue(!protection.contains("setCancelled(false)")); assertTrue(!protection.contains("Files.")); assertTrue(!protection.contains("flags.yml")); }
    @Test void rcWorkflowRequiresPrereleaseProvenanceAndPostVerification() throws Exception { String release = text(".github/workflows/release.yml"); assertTrue(release.contains("--prerelease")); assertTrue(release.contains("TEST_SUMMARY.txt")); assertTrue(release.contains("PROVENANCE.txt")); assertTrue(release.contains("runtime_certification=NOT_EXECUTED")); assertTrue(release.contains("refs/tags/$RELEASE_TAG")); assertTrue(release.contains("sha256sum --check")); }
    private static String text(String path) throws Exception { return Files.readString(Path.of(path)); }
}
